export const CHAMPIONS = [
  {
    name: "Jérémie Droz",
    skills: ["creative", "practical"],
    headline: "champion_headline_jeremie",
    src: "/assets/videos/droz-45.mov",
  },
  {
    name: "Samuel Binder",
    skills: ["creative", "helpful"],
    headline: "",
    src: "/assets/videos/binder-45.mov",
  },
  {
    name: "Zaid Rast",
    skills: ["practical", "helpful"],
    headline: "",
    src: "/assets/videos/rast-45.mov",
  },
  {
    name: "Philippe Dourassov",
    skills: ["creative", "logical"],
    headline: "",
    src: "/assets/videos/dourassov-45.mov",
  },
  {
    name: "Melitta Leu",
    skills: ["practical", "logical"],
    headline: "",
    src: "/assets/videos/leu-45.mov",
  },
  {
    name: "Simona Gier",
    skills: ["creative", "determined"],
    headline: "",
    src: "/assets/videos/gier-45.mov",
  },
  {
    name: "Mattia Andrea Plattner",
    skills: ["practical", "determined"],
    headline: "",
    src: "/assets/videos/plattner-45.mov",
  },
  {
    name: "Matteo Calà",
    skills: ["helpful", "determined"],
    headline: "",
    src: "/assets/videos/cala-45.mov",
  },
  {
    name: "Jana Gander",
    skills: ["logical", "determined"],
    headline: "",
    src: "/assets/videos/gander-45.mov",
  },
  {
    name: "Stefanie Fahrni",
    skills: ["creative", "persevering"],
    headline: "",
    src: "/assets/videos/fahrni-45.mov",
  },
  {
    name: "Carmen Bircher",
    skills: ["helpful", "persevering"],
    headline: "",
    src: "/assets/videos/bircher-45.mov",
  },
  {
    name: "Andrin Dobler",
    skills: ["logical", "persevering"],
    headline: "",
    src: "/assets/videos/dobler-45.mov",
  },
  {
    name: "Luca Hubmann",
    skills: ["determined", "persevering"],
    headline: "",
    src: "/assets/videos/hubmann-45.mov",
  },
];
